language: python
python:
  - "3.8"
  
branches:
  only:
    - master

before_install:
  - python -m pip install --upgrade pip
  
install:
  - pip install pytest
  - pip install -r requirements.txt
  
script:
  - pytest
  
env:
  INSTAUTO_TESTS_USERNAME: test_username
  INSTAUTO_TESTS_PASSWORD: test_password

notifications:
  email:
    recipients:
      - maros.gonda@student.tuke.sk
    on_success: always 
    on_failure: always 

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy https://git.kpi.fei.tuke.sk/mg561fr/ess
  - git push deploy