language: python
python:
  - "3.8"
  
branches:
  only:
    - master

before_install:
  - python -m pip install --upgrade pip
  
install:
  - pip install pytest
  - pip install -r requirements.txt
  
script:
  - pytest
  
env:
  INSTAUTO_TESTS_USERNAME: test_username
  INSTAUTO_TESTS_PASSWORD: test_password

notifications:
  email:
    recipients:
      - maros.gonda.mladsi@gmail.com
    on_success: always 
    on_failure: always 